### PR TITLE
visiting card no 82

### PR DESCRIPTION
**Pull request by sanket-jadhav07**

### CODE REVIEW

**Review by akankshadube08 — CHANGES_REQUESTED** [review]
classes name should be same as the sample code classes

**Review by akankshadube08 — CHANGES_REQUESTED** [review]
card 2 backgroung is not there

**Review by akankshadube08 — CHANGES_REQUESTED** [review]
card2 backgroundmissing

**Review by akankshadube08 — CHANGES_REQUESTED** [review]
in index.html file only background classes required
and all other code should be in preview.html file

**Review by KalpeshApnasite — CHANGES_REQUESTED** [review]
rename the folder name use "firstname_lastname_designno" this format

**Review by Bhosle07 — CHANGES_REQUESTED** [review]
visiting -66  visiting -72  check index .html should have required background classes . in preview. html don't use additional classes

**Pull request closed without merging**
